### ISSUE TITLE
Aimbot wont work

### ISSUE THREAD

**Issue by Ebzdyberybencjusz** [Bohemian43/z1external_public#1]
Cant bind mouse1 even when i did unbind. Aimbot with any other key wont work ;/

**Comment by Bohemian43** [comment]
Do you have any hitboxes selected other than the priority bone? That is required for the aimbot to activate.

**Comment by Bohemian43** [comment]
Sorry I totally misunderstood your problem. I just updated the keyinput class to fix it. Tell me if you have any other issues with this.

**Comment by Bohemian43** [comment]
Ignore what I said earlier. Press insert to bind to mouse1.
